name: Deploy Lambda Function

on:
  push:
    branches: [main]
  workflow_dispatch:  # Allow manual triggering

# Required for OIDC authentication and for actions/checkout
permissions:
  id-token: write
  contents: read

env:
  LAMBDA_FUNCTION_NAME: deepsearch-qubitz-v1
  AWS_REGION: us-east-1
  ECR_REPOSITORY_NAME: deepsearch-qubitz-v1-repo

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        # Option 1: Using AWS Access Keys (stored in GitHub Secrets)
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

        # Option 2: Using OIDC (uncomment below and comment above for better security)
        # role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
        # role-session-name: GitHubActions-DeployLambda
        # aws-region: ${{ env.AWS_REGION }}

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2

    - name: Create ECR repository if it doesn't exist
      run: |
        aws ecr describe-repositories --repository-names ${{ env.ECR_REPOSITORY_NAME }} >/dev/null 2>&1 || \
        aws ecr create-repository --repository-name ${{ env.ECR_REPOSITORY_NAME }}

    - name: Build and push Docker image
      id: build-image
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        IMAGE_TAG: ${{ github.sha }}
      run: |
        docker build -t $ECR_REGISTRY/${{ env.ECR_REPOSITORY_NAME }}:$IMAGE_TAG .
        docker push $ECR_REGISTRY/${{ env.ECR_REPOSITORY_NAME }}:$IMAGE_TAG
        echo "image_uri=$ECR_REGISTRY/${{ env.ECR_REPOSITORY_NAME }}:$IMAGE_TAG" >> $GITHUB_OUTPUT

    - name: Check if Lambda function exists
      id: check-function
      run: |
        if aws lambda get-function --function-name ${{ env.LAMBDA_FUNCTION_NAME }} >/dev/null 2>&1; then
          echo "exists=true" >> $GITHUB_OUTPUT
        else
          echo "exists=false" >> $GITHUB_OUTPUT
        fi

    - name: Create Lambda function (if it doesn't exist)
      if: steps.check-function.outputs.exists == 'false'
      run: |
        aws lambda create-function \
          --function-name ${{ env.LAMBDA_FUNCTION_NAME }} \
          --package-type Image \
          --code ImageUri=${{ steps.build-image.outputs.image_uri }} \
          --role ${{ secrets.LAMBDA_EXECUTION_ROLE_ARN }} \
          --timeout 900 \
          --memory-size 1024 \
          --environment Variables='{
            "AWS_REGION":"${{ env.AWS_REGION }}",
            "DEFAULT_MODEL_ID":"us.anthropic.claude-3-7-sonnet-20250219-v1:0",
            "CLAUDE_SONNET_MODEL_ID":"anthropic.claude-3-5-sonnet-20240620-v1:0"
          }' \
          --description "Deep Research Agent API deployed via GitHub Actions"

    - name: Update Lambda function code (if it exists)
      if: steps.check-function.outputs.exists == 'true'
      run: |
        aws lambda update-function-code \
          --function-name ${{ env.LAMBDA_FUNCTION_NAME }} \
          --image-uri ${{ steps.build-image.outputs.image_uri }}

    - name: Update Lambda function configuration
      if: steps.check-function.outputs.exists == 'true'
      run: |
        aws lambda update-function-configuration \
          --function-name ${{ env.LAMBDA_FUNCTION_NAME }} \
          --timeout 900 \
          --memory-size 1024 \
          --environment Variables='{
            "AWS_REGION":"${{ env.AWS_REGION }}",
            "DEFAULT_MODEL_ID":"us.anthropic.claude-3-7-sonnet-20250219-v1:0",
            "CLAUDE_SONNET_MODEL_ID":"anthropic.claude-3-5-sonnet-20240620-v1:0"
          }'

    - name: Wait for function update to complete
      run: |
        aws lambda wait function-updated --function-name ${{ env.LAMBDA_FUNCTION_NAME }}

    - name: Create or update function URL (for HTTP access)
      run: |
        # Try to create function URL, if it exists, this will fail but that's OK
        aws lambda create-function-url-config \
          --function-name ${{ env.LAMBDA_FUNCTION_NAME }} \
          --auth-type NONE \
          --cors '{
            "AllowCredentials": false,
            "AllowHeaders": ["*"],
            "AllowMethods": ["*"],
            "AllowOrigins": ["*"],
            "ExposeHeaders": ["*"],
            "MaxAge": 3600
          }' || true

        # Get the function URL
        FUNCTION_URL=$(aws lambda get-function-url-config \
          --function-name ${{ env.LAMBDA_FUNCTION_NAME }} \
          --query 'FunctionUrl' --output text)

        echo "🚀 Lambda function deployed successfully!"
        echo "📍 Function URL: $FUNCTION_URL"
        echo "📍 Function Name: ${{ env.LAMBDA_FUNCTION_NAME }}"
        echo "📍 Region: ${{ env.AWS_REGION }}"

    - name: Test the deployment
      run: |
        # Get function URL for testing
        FUNCTION_URL=$(aws lambda get-function-url-config \
          --function-name ${{ env.LAMBDA_FUNCTION_NAME }} \
          --query 'FunctionUrl' --output text)

        # Test health endpoint
        echo "Testing health endpoint..."
        curl -f "$FUNCTION_URL" || echo "Health check failed"

        echo "✅ Deployment completed!"
